import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Dreams",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="font-sans bg-gradient-to-br from-white to-neutral-50 dark:from-neutral-900 dark:to-neutral-800 text-neutral-900 dark:text-neutral-100 m-0 p-0 min-h-screen flex flex-col transition-colors duration-300">
      <header className="w-full max-w-3xl mx-auto px-4 py-8 flex items-center justify-between border-b border-neutral-200 dark:border-neutral-700">
        <h1 className="font-bold text-2xl mx-auto text-rainbow">Dreams</h1> 
      </header>
      <main className="flex-1 w-full max-w-3xl mx-auto px-4 py-8">
        {children}
      </main>
      <footer className="w-full max-w-3xl mx-auto px-4 py-6 flex justify-center border-t border-neutral-200 dark:border-neutral-700 text-sm text-neutral-500 dark:text-neutral-400">
        &copy; {new Date().getFullYear()} Pedro Eduardo Roel
      </footer>
      </body>
    </html>
  );
}
